### ISSUE TITLE
Sketch the dashboard

### ISSUE THREAD

**Issue by NikitaShymberg** [UBC-MDS/imdb_dashboard#4]

**Comment by iamMoid** [comment]
![image](https://user-images.githubusercontent.com/8488763/154552081-39cd602c-0af3-4c81-aa8d-3a7dc6b8dfe2.png)
Team, attached is the sketch of our dashboard based on our conversations. Let me know if you like more additions.

**Comment by ming0701** [comment]
Thanks Moid. Some comments below in order to match our motivation and usage in the proposal.
- Typo in the header: IMDB instead of IMBD
- For the map, should we use average movie rating instead of runtime?
- For the top left chart, should we show movie "rating" by genre of a particular year (boxplot) instead of proportion of movies by genre? So we have one chart showing the detailed ratings of the genre of a particular year (top left) and one chart showing the average rating by genre over time (top right)
- [for discussion] We can't put all filters in the control panel? Some of the filters are applicable to one chart only. E.g. actor filter should apply to actor chart only.

**Comment by NikitaShymberg** [comment]
I mostly agree with @ming0701's comments but I think it is sensible to have all the filters in the control panel. For example we might want to set the actor globally to see what kinds of genres they act in and maybe which countires.

That being said, maybe it's a good idea to have a separate actor drop-down for the actor chart (or is that too confusing?)

Edit: one other thing worth mentioning is that this sketch doesn't have to be completely perfect - we're allowed to make some chages during implementation.

**Comment by ming0701** [comment]
@NikitaShymberg Yes, true. Let's leave the control panel as it is first. I think we will have more ideas when we build the app.

**Comment by iamMoid** [comment]
Thanks for the feedback guys. My prior dashboarding experiences confirm:
1. A dashboard looks better organized with all filters/sliders in the control panel to avoid clutter or placement issues on the main plot area. 
2. If a filter is specific to a plot, we typically add a note just above that filter itself to indicate the same.
3. Agree with @NikitaShymberg, I am pretty confident we are at liberty to try multiple filters/variations/plots when we build the app. The sketch is just to give an overall idea of the direction we are headed in.
4. To your point @ming0701 regarding the metric choice for the graphs, my idea is to incorporate the ability to switch between metrics on the same plot. For e.g., we can add an option/radio button control to switch the metric on the plots between 'Average Rating' or 'Average Runtime' or 'Count of Movies', etc. If we are not able to achieve this, we can choose the best metric for each plot. For the time being, I will leave it as is just to keep the idea open that we can have different metrics.
